name: Test Build and Lint

# This workflow will run the linter, then build the application and ensure there are no build errors
on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: pass environment variables
        uses: actions/setup-node@v4
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUB_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
          OPENAPI_API_KEY: ${{secrets.OPENAI_API_KEY}}

      - name: Install dependencies and run lint and build
        run: |
          echo CLERK_PUB_KEY
          npm install
          npm run build --if-present
          npm run lint
